language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install --upgrade pip
- pip install coveralls
- pip install -r requirements_dev.txt
- pip install . --no-deps
script:
- py.test
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  on:
    tags: true
after_success:
- coveralls
